version: '3.7'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sonarqube}
      POSTGRES_USER: ${POSTGRES_USER:-sonarqube}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please set password for database user 'sonarqube'}
  sonarqube:
    image: sonarqube:8.2-community
    volumes:
      - /srv/sonarqube/data:/opt/sonarqube/data
      - /srv/sonarqube/logs:/opt/sonarqube/logs
      - /srv/sonarqube/extensions:/opt/sonarqube/extensions
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${POSTGRES_USER}
      SONAR_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 9000:9000
    depends_on:
      - postgres